### ISSUE TITLE
Tests on Prusa Protective Face Shield - RC3

### ISSUE THREAD

**Issue by cotontigeh** [bneiluj/covid-19-open-source-masks#8]
### Description
I testing the prusa face shield.
The shield is strong but stay flexible enought

I'm waiting the delivery for the front glass, i keep this issue updated when i receive this and build the entire mask.

### Configuration
i have a good result with RC3 and this is my configuration : 

- Printer : **Prusa MK3S**
- Speed : **120 mm/s**
- Infill : **20%**
- Shields : **4**
- Material : **PLA** from **Ice Filament**
- Temperature : **210 °C**
- Printing time: **3h**
- Supports: **No supports**

### Todo 

- [x] Print RC3 part
- [x] Attach transparent plastic
- [x] Find a way to attach the structure to the head 
- [x] Make holes in transparent plastic 

![IMG_20200330_170148](https://user-images.githubusercontent.com/26523097/77930554-52105e80-72ab-11ea-9a78-4cb23ff41ce5.jpg)
![IMG_20200330_170132](https://user-images.githubusercontent.com/26523097/77930558-52a8f500-72ab-11ea-86b7-bf5cae0a6c95.jpg)
![IMG_20200330_170140](https://user-images.githubusercontent.com/26523097/77930559-53418b80-72ab-11ea-9109-5bafed7c6086.jpg)

**Comment by cotontigeh** [comment]
I give a try to a strap band for the attach of the mask and it work perfectly ! 

no matter the size (mine is 5cm width) 

i make a node and it's strong enought to be weared 

![IMG_20200331_152230](https://user-images.githubusercontent.com/26523097/78037063-53a15b80-736b-11ea-8e6f-ebcffa8bf245.jpg)
![IMG_20200331_152109](https://user-images.githubusercontent.com/26523097/78037065-54d28880-736b-11ea-9f21-94284ddb57fd.jpg)
![IMG_20200331_152116](https://user-images.githubusercontent.com/26523097/78037066-54d28880-736b-11ea-936b-e28bfc02f9a9.jpg)

**Comment by Delnaraxe** [comment]
Hi, as requested by @cotontigeh  i tested the .STL (PRUSA face shield RC3) on a crealityCR10S.
Object seems OK as expected, i have an export of my configuration ready via prusa slicer available for anyone who need it.
Otherwise here some of my prints settings : 
• Printing time : 4 hours 7 minutes for 1 shield
• Layer height 0.2mm
• 4 walls or perimeters
• 4 layers for TOP & BOTTOM
• 20% for infill with gyroïde pattern
• NO SUPPORTS
• Speed is : - 60mm/s for walls
                   - 30mm/s for external wall
                   - 20mm/s for solid infill
• Temperature is 200°c for my filament (Eryone filament PLA) and 60°c for bed temperature with cooling fan activated.

Still i do not recommend to use it for medical purpose since there is some cavities with FDM printers that could lead to contamination but i would give it to anyone exposed and in the need of protection at LYON.

![20200331_162623](https://user-images.githubusercontent.com/62946561/78041253-bfd28e00-7370-11ea-8ffc-dda902a335c6.jpg)
![20200331_162605](https://user-images.githubusercontent.com/62946561/78041255-c06b2480-7370-11ea-93e0-937f6058e331.jpg)
![20200331_162726](https://user-images.githubusercontent.com/62946561/78041257-c103bb00-7370-11ea-9e5e-7c3904456611.jpg)
![20200331_162720](https://user-images.githubusercontent.com/62946561/78041261-c19c5180-7370-11ea-8df1-ba6b0e27f038.jpg)

**Comment by cotontigeh** [comment]
Hi,

I finally got some PVC film and build some mask , it's 150 micron width

that's work very well ! 

i go deliver a private hospital friday for a total of 100 mask

if you have questions about the construction don't hesitate ! 

![IMG_3025](https://user-images.githubusercontent.com/26523097/78185945-2ab4bf80-746c-11ea-8ef9-c06374d1ebab.jpg)

**Comment by bneiluj** [comment]
That's really awesome. 

Regarding the funding, we need: 

- One photo of the group wearing the masks (if they agree)
- A signed letter from the hospital (to discharge responsibilities and proof for the grant)
